import { useCallback, useEffect, useState } from "react";
import Dashboard from "../components/Dashboard";
import DataQualityPanel from "../components/DataQualityPanel";
import DecisionIntelPanel from "../components/DecisionIntelPanel";
import DatasetSummary from "../components/DatasetSummary";
import FileUpload from "../components/FileUpload";
import InsightPanel from "../components/InsightPanel";
import LoadingSpinner from "../components/LoadingSpinner";
import PromptInput from "../components/PromptInput";
import RecommendationPanel from "../components/RecommendationPanel";
import SimulationPanel from "../components/SimulationPanel";
import WidgetModal from "../components/WidgetModal";
import {
  autogenerateDashboard,
  explainChart,
  editChart,
  followUp,
  generateDashboard,
  getCorrelations,
  getDatasetProfile,
  getQualityReport,
  getRootCause,
  simulateScenario,
  uploadCsv
} from "../services/api";
import { generateExecutiveReport } from "../services/reportApi";
import { useSocket } from "../hooks/useSocket";

function normalizeWidget(response, index = 0) {
  const id = response.widget_id || `widget-${Date.now()}-${index}`;
  const metadata = response.metadata || response.chart_metadata || {};
  return {
    id,
    jobId: response.job_id || null,
    title: response.title || response.prompt || "Generated Chart",
    sourcePrompt: response.sourcePrompt || response.source_prompt || response.prompt || response.title || "",
    chartType: response.chartType || response.chart_type,
    data: response.data || [],
    analysisLoading: Boolean(response.analysis_pending),
    metadata: {
      ...metadata,
      anomalies: response.anomalies || metadata.anomalies || []
    },
    layout: response.layout || { i: id, x: (index * 6) % 12, y: Infinity, w: 6, h: 8 }
  };
}

function withExpandedExplanationLayout(widget, explanation) {
  const minimumHeight = widget.chartType === "table" ? 12 : 11;
  const extraRows = Math.min(Math.max((explanation?.length || 0) - 2, 0), 2);
  return {
    ...widget,
    explanation,
    explanationLoading: false,
    layout: {
      ...widget.layout,
      h: Math.max(widget.layout?.h || 8, minimumHeight + extraRows)
    }
  };
}

function Home() {
  const [widgets, setWidgets] = useState([]);
  const [loading, setLoading] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [insight, setInsight] = useState("");
  const [sql, setSql] = useState("");
  const [chartType, setChartType] = useState("");
  const [dataset, setDataset] = useState("sales_data");
  const [datasetProfile, setDatasetProfile] = useState(null);
  const [hasUploadedDataset, setHasUploadedDataset] = useState(false);
  const [summaryCards, setSummaryCards] = useState([]);
  const [suggestedPrompts, setSuggestedPrompts] = useState([]);
  const [qualityReport, setQualityReport] = useState(null);
  const [correlations, setCorrelations] = useState([]);
  const [rootCause, setRootCause] = useState(null);
  const [simulation, setSimulation] = useState(null);
  const [simulationLoading, setSimulationLoading] = useState(false);
  const [chartEditLoading, setChartEditLoading] = useState(false);
  const [recommendations, setRecommendations] = useState([]);
  const [reportLoading, setReportLoading] = useState(false);
  const [reportPreview, setReportPreview] = useState(null);
  const [analysisPending, setAnalysisPending] = useState(false);
  const [prompt, setPrompt] = useState("");
  const [expandedWidget, setExpandedWidget] = useState(null);
  const [annotationsByWidget, setAnnotationsByWidget] = useState({});
  const [error, setError] = useState("");
  const [sessionId] = useState(() => crypto.randomUUID());

  const handleDashboardEvent = useCallback((payload) => {
    if (payload?.widgets) {
      setWidgets(payload.widgets.map(normalizeWidget));
    }
    if (payload?.insight) {
      setInsight(payload.insight);
    }
    if (payload?.summary_cards) {
      setSummaryCards(payload.summary_cards);
    }
    if (payload?.follow_up_prompts) {
      setSuggestedPrompts(payload.follow_up_prompts);
    }
    if (payload?.recommendations) {
      setRecommendations(payload.recommendations);
    }
    if (typeof payload?.analysis_pending === "boolean") {
      setAnalysisPending(payload.analysis_pending);
    }
    if (payload?.root_cause) {
      setRootCause(payload.root_cause);
    }
    if (payload?.correlations) {
      setCorrelations(payload.correlations);
    }
  }, []);

  const handleAnalysisEvent = useCallback((payload) => {
    if (payload?.error) {
      setError(payload.error);
    }
    if (payload?.root_cause) {
      setRootCause(payload.root_cause);
    }
    if (payload?.correlations) {
      setCorrelations(payload.correlations);
    }
    if (payload?.recommendations) {
      setRecommendations(payload.recommendations);
    }
    if (payload?.insight) {
      setInsight(payload.insight);
    }
    setAnalysisPending(Boolean(payload?.analysis_pending));
    if (payload?.widget_id) {
      setWidgets((current) =>
        current.map((widget) =>
          widget.id === payload.widget_id
            ? {
                ...widget,
                analysisLoading: false,
                metadata: {
                  ...widget.metadata,
                  anomalies: payload.anomalies || widget.metadata?.anomalies || []
                }
              }
            : widget
        )
      );
      setExpandedWidget((current) =>
        current && current.id === payload.widget_id
          ? {
              ...current,
              analysisLoading: false,
              metadata: {
                ...current.metadata,
                anomalies: payload.anomalies || current.metadata?.anomalies || []
              }
            }
          : current
      );
    }
  }, []);

  const { socket, isConnected } = useSocket(sessionId, handleDashboardEvent, handleAnalysisEvent);

  useEffect(() => {
    if (!socket) {
      return;
    }

    socket.emit("join_session", { session_id: sessionId });
  }, [sessionId, socket]);

  const submitPrompt = async (prompt, isFollowUp = false) => {
    setLoading(true);
    setError("");
    setAnalysisPending(false);
    setRootCause(null);
    setRecommendations([]);
    setCorrelations([]);

    try {
      const payload = { prompt, session_id: sessionId };
      const response = isFollowUp
        ? await followUp(payload)
        : await generateDashboard(payload);

      const nextWidget = normalizeWidget({ ...response, prompt }, widgets.length);
      const nextWidgets = response.replace_dashboard ? [nextWidget] : [...widgets, nextWidget];

      setWidgets(nextWidgets);
      setInsight(response.insight);
      setSummaryCards(response.summary_cards || []);
      setSuggestedPrompts(response.follow_up_prompts || []);
      setRootCause(response.root_cause || null);
      setSql(response.sql);
      setChartType(response.chart_type);
      setDataset(response.dataset || dataset);
      setPrompt(prompt);
      setAnalysisPending(Boolean(response.analysis_pending));
      if (hasUploadedDataset && response.dataset && response.dataset !== dataset) {
        const profile = await getDatasetProfile(sessionId);
        setDatasetProfile(profile);
      }

      socket?.emit("dashboard_update", {
        session_id: sessionId,
        widgets: nextWidgets,
        insight: response.insight,
        summary_cards: response.summary_cards || [],
        follow_up_prompts: response.follow_up_prompts || [],
        recommendations: [],
        analysis_pending: Boolean(response.analysis_pending)
      });
    } catch (requestError) {
      setError(
        requestError?.response?.data?.error ||
          "Sorry, the system could not answer this query using the available dataset."
      );
    } finally {
      setLoading(false);
    }
  };

  const handleUpload = async (file) => {
    setUploading(true);
    setError("");
    try {
      const response = await uploadCsv(file, sessionId);
      setDataset(response.table_name);
      setDatasetProfile(response.profile || null);
      setHasUploadedDataset(true);
      const [quality, correlationData, autogen] = await Promise.all([
        getQualityReport(sessionId),
        getCorrelations(sessionId),
        autogenerateDashboard({ session_id: sessionId })
      ]);
      setQualityReport(quality);
      setCorrelations(correlationData.correlations || []);
      setWidgets((autogen.widgets || []).map(normalizeWidget));
      setSql("");
      setChartType("");
      setSummaryCards(autogen.summary_cards || []);
      setSuggestedPrompts([]);
      setRootCause(null);
      setSimulation(null);
      setRecommendations([]);
      setAnalysisPending(false);
      setInsight(
        autogen.insight ||
          `Dataset ${response.table_name} uploaded successfully with ${response.row_count} rows, ${response.columns.length} columns, and ${response.encoding} encoding. Ask a question about this data next.`
      );
    } catch (uploadError) {
      setDatasetProfile(null);
      setHasUploadedDataset(false);
      setQualityReport(null);
      setCorrelations([]);
      setRecommendations([]);
      setAnalysisPending(false);
      setError(uploadError?.response?.data?.error || "CSV upload failed.");
    } finally {
      setUploading(false);
    }
  };

  const handleLayoutsChange = (layout) => {
    setWidgets((current) =>
      current.map((widget) => ({
        ...widget,
        layout: layout.find((item) => item.i === widget.id) || widget.layout
      }))
    );
  };

  const handleFilterChange = (widgetId, range) => {
    socket?.emit("filter_change", { session_id: sessionId, widget_id: widgetId, range });
  };

  const handleAddAnnotation = (widgetId, note) => {
    setAnnotationsByWidget((current) => ({
      ...current,
      [widgetId]: [...(current[widgetId] || []), note]
    }));
  };

  const handleChartTypeChange = (widgetId, nextType) => {
    setWidgets((current) =>
      current.map((widget) =>
        widget.id === widgetId ? { ...widget, chartType: nextType } : widget
      )
    );
    setExpandedWidget((current) =>
      current && current.id === widgetId ? { ...current, chartType: nextType } : current
    );
  };

  const handleExplainChart = async (widget) => {
    setWidgets((current) =>
      current.map((item) =>
        item.id === widget.id ? { ...item, explanationLoading: true } : item
      )
    );
    setExpandedWidget((current) =>
      current && current.id === widget.id ? { ...current, explanationLoading: true } : current
    );

    try {
      const response = await explainChart({
        widget_id: widget.id,
        chart_data: widget.data,
        chart_type: widget.chartType,
        metadata: widget.metadata
      });
      setWidgets((current) =>
        current.map((item) =>
          item.id === widget.id
            ? withExpandedExplanationLayout(item, response.explanation || [])
            : item
        )
      );
      setExpandedWidget((current) =>
        current && current.id === widget.id
          ? withExpandedExplanationLayout(current, response.explanation || [])
          : current
      );
    } catch (_error) {
      setWidgets((current) =>
        current.map((item) =>
          item.id === widget.id
            ? withExpandedExplanationLayout(
                item,
                ["The system could not generate a chart explanation right now."]
              )
            : item
        )
      );
      setExpandedWidget((current) =>
        current && current.id === widget.id
          ? withExpandedExplanationLayout(
              current,
              ["The system could not generate a chart explanation right now."]
            )
          : current
      );
    }
  };

  const handleSimulation = async (scenarioPrompt) => {
    setSimulationLoading(true);
    try {
      const response = await simulateScenario({ session_id: sessionId, prompt: scenarioPrompt });
      setSimulation(response.simulation || null);
    } finally {
      setSimulationLoading(false);
    }
  };

  const handleChartEdit = async (widget, editPrompt) => {
    setChartEditLoading(true);
    try {
      const updated = await editChart({ widget, edit_prompt: editPrompt });
      const normalized = normalizeWidget(updated);
      setWidgets((current) =>
        current.map((item) => (item.id === widget.id ? { ...item, ...normalized, id: widget.id } : item))
      );
      setExpandedWidget((current) =>
        current && current.id === widget.id ? { ...current, ...normalized, id: widget.id } : current
      );
    } finally {
      setChartEditLoading(false);
    }
  };

  const handleRunRootCause = async () => {
    const response = await getRootCause({ session_id: sessionId, prompt });
    setRootCause(response);
  };

  const handleGenerateReport = async () => {
    setReportLoading(true);
    try {
      const response = await generateExecutiveReport({
        dataset,
        insight,
        summary_cards: summaryCards,
        widgets,
        root_cause: rootCause,
        anomalies: widgets.flatMap((widget) => widget.metadata?.anomalies || []),
        correlations,
        recommendations,
        simulation
      });
      setReportPreview(response);
    } finally {
      setReportLoading(false);
    }
  };

  const handleDownloadReportPdf = () => {
    if (!reportPreview?.pdf_base64) {
      return;
    }
    const link = document.createElement("a");
    link.href = `data:application/pdf;base64,${reportPreview.pdf_base64}`;
    link.download = reportPreview.filename || "executive-report.pdf";
    link.click();
  };

  const handleDownloadReportMarkdown = () => {
    if (!reportPreview?.markdown) {
      return;
    }
    const blob = new Blob([reportPreview.markdown], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "executive-report.md";
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <main className="min-h-screen px-4 py-8 text-slate-100 md:px-8">
      <div className="mx-auto flex max-w-7xl flex-col gap-6">
        <header className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
          <div>
            <p className="text-xs uppercase tracking-[0.35em] text-signal">AI-native BI</p>
            <h1 className="font-display text-4xl font-semibold text-white">
              Natural Language Dashboard Studio
            </h1>
          </div>
          <div className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs text-slate-300">
            Session {isConnected ? "live" : "offline"} | Dataset: {dataset}
          </div>
        </header>

        <PromptInput
          onSubmit={(nextPrompt) => submitPrompt(nextPrompt, widgets.length > 0)}
          loading={loading}
          prompt={prompt}
          onPromptChange={setPrompt}
          suggestedPrompts={suggestedPrompts}
        />
        <FileUpload onUpload={handleUpload} uploading={uploading} />
        {loading && <LoadingSpinner />}
        {hasUploadedDataset && <DatasetSummary profile={datasetProfile} />}
        {hasUploadedDataset && <DataQualityPanel report={qualityReport} />}
        {hasUploadedDataset && (
          <SimulationPanel onSimulate={handleSimulation} loading={simulationLoading} />
        )}
        <Dashboard
          widgets={widgets}
          onLayoutsChange={handleLayoutsChange}
          onFilterChange={handleFilterChange}
          onMaximizeWidget={setExpandedWidget}
          onChartTypeChange={handleChartTypeChange}
          onExplainChart={handleExplainChart}
          onGenerateReport={handleGenerateReport}
          reportLoading={reportLoading}
          reportPreview={reportPreview}
          onCloseReport={() => setReportPreview(null)}
          onDownloadReportPdf={handleDownloadReportPdf}
          onDownloadReportMarkdown={handleDownloadReportMarkdown}
        />
        <InsightPanel
          insight={insight}
          sql={sql}
          chartType={chartType}
          dataset={dataset}
          error={error}
          summaryCards={summaryCards}
          loading={analysisPending}
        />
        <RecommendationPanel recommendations={recommendations} loading={analysisPending} />
        <DecisionIntelPanel
          rootCause={rootCause}
          correlations={correlations}
          simulation={simulation}
          loading={analysisPending}
        />
        {hasUploadedDataset && (
          <div className="flex justify-end">
            <button
              type="button"
              onClick={handleRunRootCause}
              className="rounded-full border border-white/10 bg-white/10 px-4 py-2 text-sm text-slate-100 hover:bg-white/20"
            >
              Run Root Cause Analysis
            </button>
          </div>
        )}
      </div>
      <WidgetModal
        widget={expandedWidget}
        annotations={expandedWidget ? annotationsByWidget[expandedWidget.id] || [] : []}
        onAddAnnotation={handleAddAnnotation}
        onChartTypeChange={handleChartTypeChange}
        onExplainChart={handleExplainChart}
        onEditChart={handleChartEdit}
        editLoading={chartEditLoading}
        onClose={() => setExpandedWidget(null)}
      />
    </main>
  );
}

export default Home;
