import { useCallback, useEffect, useState } from "react";
import Dashboard from "../components/Dashboard";
import DataQualityPanel from "../components/DataQualityPanel";
import DecisionIntelPanel from "../components/DecisionIntelPanel";
import DatasetSummary from "../components/DatasetSummary";
import FileUpload from "../components/FileUpload";
import InsightPanel from "../components/InsightPanel";
import LoadingSpinner from "../components/LoadingSpinner";
import PromptInput from "../components/PromptInput";
import SimulationPanel from "../components/SimulationPanel";
import WidgetModal from "../components/WidgetModal";
import {
  autogenerateDashboard,
  editChart,
  followUp,
  generateDashboard,
  getCorrelations,
  getDatasetProfile,
  getQualityReport,
  getRootCause,
  simulateScenario,
  uploadCsv
} from "../services/api";
import { useSocket } from "../hooks/useSocket";

function normalizeWidget(response, index = 0) {
  const id = response.widget_id || `widget-${Date.now()}-${index}`;
  const metadata = response.metadata || response.chart_metadata || {};
  return {
    id,
    title: response.title || response.prompt || "Generated Chart",
    sourcePrompt: response.sourcePrompt || response.source_prompt || response.prompt || response.title || "",
    chartType: response.chartType || response.chart_type,
    data: response.data || [],
    metadata: {
      ...metadata,
      anomalies: response.anomalies || metadata.anomalies || []
    },
    layout: response.layout || { i: id, x: (index * 6) % 12, y: Infinity, w: 6, h: 8 }
  };
}

function Home() {
  const [widgets, setWidgets] = useState([]);
  const [loading, setLoading] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [insight, setInsight] = useState("");
  const [sql, setSql] = useState("");
  const [chartType, setChartType] = useState("");
  const [dataset, setDataset] = useState("sales_data");
  const [datasetProfile, setDatasetProfile] = useState(null);
  const [hasUploadedDataset, setHasUploadedDataset] = useState(false);
  const [summaryCards, setSummaryCards] = useState([]);
  const [suggestedPrompts, setSuggestedPrompts] = useState([]);
  const [qualityReport, setQualityReport] = useState(null);
  const [correlations, setCorrelations] = useState([]);
  const [rootCause, setRootCause] = useState(null);
  const [simulation, setSimulation] = useState(null);
  const [simulationLoading, setSimulationLoading] = useState(false);
  const [chartEditLoading, setChartEditLoading] = useState(false);
  const [prompt, setPrompt] = useState(
    "Show monthly revenue trends for 2024 and highlight the best performing region"
  );
  const [expandedWidget, setExpandedWidget] = useState(null);
  const [annotationsByWidget, setAnnotationsByWidget] = useState({});
  const [error, setError] = useState("");
  const [sessionId] = useState(() => crypto.randomUUID());

  const handleDashboardEvent = useCallback((payload) => {
    if (payload?.widgets) {
      setWidgets(payload.widgets.map(normalizeWidget));
    }
    if (payload?.insight) {
      setInsight(payload.insight);
    }
    if (payload?.summary_cards) {
      setSummaryCards(payload.summary_cards);
    }
    if (payload?.follow_up_prompts) {
      setSuggestedPrompts(payload.follow_up_prompts);
    }
  }, []);

  const { socket, isConnected } = useSocket(sessionId, handleDashboardEvent);

  useEffect(() => {
    if (!socket) {
      return;
    }

    socket.emit("join_session", { session_id: sessionId });
  }, [sessionId, socket]);

  const submitPrompt = async (prompt, isFollowUp = false) => {
    setLoading(true);
    setError("");

    try {
      const payload = { prompt, session_id: sessionId };
      const response = isFollowUp
        ? await followUp(payload)
        : await generateDashboard(payload);

      const nextWidget = normalizeWidget({ ...response, prompt }, widgets.length);
      const nextWidgets = response.replace_dashboard ? [nextWidget] : [...widgets, nextWidget];

      setWidgets(nextWidgets);
      setInsight(response.insight);
      setSummaryCards(response.summary_cards || []);
      setSuggestedPrompts(response.follow_up_prompts || []);
      setRootCause(response.root_cause || null);
      setSql(response.sql);
      setChartType(response.chart_type);
      setDataset(response.dataset || dataset);
      setPrompt(prompt);
      if (hasUploadedDataset && response.dataset && response.dataset !== dataset) {
        const profile = await getDatasetProfile(sessionId);
        setDatasetProfile(profile);
      }

      socket?.emit("dashboard_update", {
        session_id: sessionId,
        widgets: nextWidgets,
        insight: response.insight,
        summary_cards: response.summary_cards || [],
        follow_up_prompts: response.follow_up_prompts || []
      });
    } catch (requestError) {
      setError(
        requestError?.response?.data?.error ||
          "Sorry, the system could not answer this query using the available dataset."
      );
    } finally {
      setLoading(false);
    }
  };

  const handleUpload = async (file) => {
    setUploading(true);
    setError("");
    try {
      const response = await uploadCsv(file, sessionId);
      setDataset(response.table_name);
      setDatasetProfile(response.profile || null);
      setHasUploadedDataset(true);
      const [quality, correlationData, autogen] = await Promise.all([
        getQualityReport(sessionId),
        getCorrelations(sessionId),
        autogenerateDashboard({ session_id: sessionId })
      ]);
      setQualityReport(quality);
      setCorrelations(correlationData.correlations || []);
      setWidgets((autogen.widgets || []).map(normalizeWidget));
      setSql("");
      setChartType("");
      setSummaryCards(autogen.summary_cards || []);
      setSuggestedPrompts([]);
      setRootCause(null);
      setSimulation(null);
      setInsight(
        autogen.insight ||
          `Dataset ${response.table_name} uploaded successfully with ${response.row_count} rows, ${response.columns.length} columns, and ${response.encoding} encoding. Ask a question about this data next.`
      );
    } catch (uploadError) {
      setDatasetProfile(null);
      setHasUploadedDataset(false);
      setQualityReport(null);
      setCorrelations([]);
      setError(uploadError?.response?.data?.error || "CSV upload failed.");
    } finally {
      setUploading(false);
    }
  };

  const handleLayoutsChange = (layout) => {
    setWidgets((current) =>
      current.map((widget) => ({
        ...widget,
        layout: layout.find((item) => item.i === widget.id) || widget.layout
      }))
    );
  };

  const handleFilterChange = (widgetId, range) => {
    socket?.emit("filter_change", { session_id: sessionId, widget_id: widgetId, range });
  };

  const handleAddAnnotation = (widgetId, note) => {
    setAnnotationsByWidget((current) => ({
      ...current,
      [widgetId]: [...(current[widgetId] || []), note]
    }));
  };

  const handleChartTypeChange = (widgetId, nextType) => {
    setWidgets((current) =>
      current.map((widget) =>
        widget.id === widgetId ? { ...widget, chartType: nextType } : widget
      )
    );
    setExpandedWidget((current) =>
      current && current.id === widgetId ? { ...current, chartType: nextType } : current
    );
  };

  const handleSimulation = async (scenarioPrompt) => {
    setSimulationLoading(true);
    try {
      const response = await simulateScenario({ session_id: sessionId, prompt: scenarioPrompt });
      setSimulation(response.simulation || null);
    } finally {
      setSimulationLoading(false);
    }
  };

  const handleChartEdit = async (widget, editPrompt) => {
    setChartEditLoading(true);
    try {
      const updated = await editChart({ widget, edit_prompt: editPrompt });
      const normalized = normalizeWidget(updated);
      setWidgets((current) =>
        current.map((item) => (item.id === widget.id ? { ...item, ...normalized, id: widget.id } : item))
      );
      setExpandedWidget((current) =>
        current && current.id === widget.id ? { ...current, ...normalized, id: widget.id } : current
      );
    } finally {
      setChartEditLoading(false);
    }
  };

  const handleRunRootCause = async () => {
    const response = await getRootCause({ session_id: sessionId, prompt });
    setRootCause(response);
  };

  return (
    <main className="min-h-screen px-4 py-8 text-slate-100 md:px-8">
      <div className="mx-auto flex max-w-7xl flex-col gap-6">
        <header className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
          <div>
            <p className="text-xs uppercase tracking-[0.35em] text-signal">AI-native BI</p>
            <h1 className="font-display text-4xl font-semibold text-white">
              Natural Language Dashboard Studio
            </h1>
          </div>
          <div className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs text-slate-300">
            Session {isConnected ? "live" : "offline"} | Dataset: {dataset}
          </div>
        </header>

        <PromptInput
          onSubmit={(nextPrompt) => submitPrompt(nextPrompt, widgets.length > 0)}
          loading={loading}
          prompt={prompt}
          onPromptChange={setPrompt}
          suggestedPrompts={suggestedPrompts}
        />
        <FileUpload onUpload={handleUpload} uploading={uploading} />
        {loading && <LoadingSpinner />}
        {hasUploadedDataset && <DatasetSummary profile={datasetProfile} />}
        {hasUploadedDataset && <DataQualityPanel report={qualityReport} />}
        {hasUploadedDataset && (
          <SimulationPanel onSimulate={handleSimulation} loading={simulationLoading} />
        )}
        <Dashboard
          widgets={widgets}
          onLayoutsChange={handleLayoutsChange}
          onFilterChange={handleFilterChange}
          onMaximizeWidget={setExpandedWidget}
          onChartTypeChange={handleChartTypeChange}
        />
        <InsightPanel
          insight={insight}
          sql={sql}
          chartType={chartType}
          dataset={dataset}
          error={error}
          summaryCards={summaryCards}
        />
        <DecisionIntelPanel
          rootCause={rootCause}
          correlations={correlations}
          simulation={simulation}
        />
        {hasUploadedDataset && (
          <div className="flex justify-end">
            <button
              type="button"
              onClick={handleRunRootCause}
              className="rounded-full border border-white/10 bg-white/10 px-4 py-2 text-sm text-slate-100 hover:bg-white/20"
            >
              Run Root Cause Analysis
            </button>
          </div>
        )}
      </div>
      <WidgetModal
        widget={expandedWidget}
        annotations={expandedWidget ? annotationsByWidget[expandedWidget.id] || [] : []}
        onAddAnnotation={handleAddAnnotation}
        onChartTypeChange={handleChartTypeChange}
        onEditChart={handleChartEdit}
        editLoading={chartEditLoading}
        onClose={() => setExpandedWidget(null)}
      />
    </main>
  );
}

export default Home;
